### ISSUE TITLE
Update GUI client-side dependencies

### ISSUE THREAD

**Issue by yamalight** [hobbit-project/platform#104]
There's more than 35 outdated packages in current GUI version.
I'd highly suggest we update them primarily for security reason. Old version might contain security vulnerabilities (esp. angular modules), would be good to patch them out.

**Comment by yamalight** [comment]
OK, that was actually cache issue, it does builds fine under 8.4.0 😂

**Comment by Ennosigaeon** [comment]
Resolution for this issue is available in branch [angular4](/hobbit-project/platform/tree/angular4). Please note, that this is a major rewrite of the angular frontend logic and requires some testing before deploying to production.

Furthermore, this branch contains solutions to various other issues (see list of referenced issues).
