### ISSUE TITLE
Back button no longer navigates to the correct page

### ISSUE THREAD

**Issue by denkv** [hobbit-project/platform#138]
- go to leaderboard for any task of any challenge
- check some experiments, use "show details" button
- use "back" button

Expected leaderboard, got experiment list.

**Comment by Ennosigaeon** [comment]
I have changed the behaviour of all back buttons to return to the previous location instead of hard-coded components.

**Comment by denkv** [comment]
`Back` button navigates to the same page on "Register Systems for Challenge" page:

http://master.project-hobbit.eu/challenges/http:%2F%2Fw3id.org%2Fhobbit%2Fchallenges%23c1753ec4-6b6a-48e4-bb8e-d69c6f212e02/register

**Comment by Ennosigaeon** [comment]
This only happens if you directly navigate to the link you have posted. I am using `location.back()` on clicking the back button. If this is the first page you have openend and you are already logged in, the back button opens the keycloak url, which directly forwards you to that page again, as you are already logged in.

If you however first open any challenge, click on register systems and then use the back button it works as intended.

I don't think that I can fix that behaviour easily and the described case should seldom occure.

**Comment by MichaelRoeder** [comment]
I think these special cases don't have to be fixed. Thanks to both of you for checking it in detail :smiley:

**Comment by denkv** [comment]
"Back" button could have the logic of "go to the parent item" where possible (viewing single task of challenge, for example). It can be a kind of breadcrumb link instead of just "back".
