### ISSUE TITLE
Empty logs

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#271]
Hi all, 

Sorry, for duplicating problems, but [log files are empty](https://github.com/hobbit-project/DEBS-GC-2018/issues/25). 

Thank you!

**Comment by MichaelRoeder** [comment]
The issue is caused by a growing index that causes Elasticsearch to terminate the retrieval of logs because it would consume more memory than Elasticsearch has available. We are currently working on a solution by restricting the search for the log messages based on the time at which an experiment was running.

**Comment by earthquakesan** [comment]
The issue should be resolved right now. @smirnp
