### ISSUE TITLE
Drop down menu for specific value parameters

### ISSUE THREAD

**Issue by vpapako** [hobbit-project/platform#28]
When benchmarking a system, it would be helpfull to have a drop down menu for configuration parameters that restricted to get their value from a set of specific ones (e.g. through owl:oneOf in their definition in benchmark.ttl)

**Comment by MichaelRoeder** [comment]
This is already implemented.
https://github.com/hobbit-project/platform/wiki/Benchmark-meta-data-file#parameters

Please have a look at the `<http://www.example.org/exampleBenchmark/graphPattern>` example and close this issue if this is what you need. Otherwise, you might want to rephrase the description of the issue.
