### ISSUE TITLE
Results of Hidden challenges are available

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#309]
Hidden challenges [(example)](https://master.project-hobbit.eu/challenges/http:%2F%2Fw3id.org%2Fhobbit%2Fchallenges%2333578642-2a74-4a95-8f9b-24a6f675937f) are accessible via link in Experiment Status (during execution) and results of hidden challenge appear in results table BEFORE the publication date.

This is very critical, since we want to announce winner at the awarding...

**Comment by smirnp** [comment]
Actually not. The challenge changes are also not saved in DB

**Comment by MichaelRoeder** [comment]
## 1. Hidden challenges are accessible via link in experiment status

This is possible because it was not foreseen that a "hidden" challenge is executed. The workflow for challenges was designed for the steps:
1. create the challenge and its task
2. make it visible for others
3. participants register their systems
4. the challenge is closed
5. the challenge is executed
6. the challenge results are published

In your example, step 2 never happened and the challenge is still "hidden". However, based on that step 3 wouldn't be possible as well.

## 2. Results are visible before publication

The results are listed in the table. However, when an "unauthorized" user (i.e., neither the challenge owner nor the system owner) tries to open the experiment, it shouldn't be visible to him. This was checked several times and should work. Please let me know if you have an example which shows that it is not working.

**Comment by smirnp** [comment]
> 2. Results are visible before publication

I have just hide the [Training Challenge](https://master.project-hobbit.eu/challenges/http:%2F%2Fw3id.org%2Fhobbit%2Fchallenges%2333578642-2a74-4a95-8f9b-24a6f675937f) and don't see it in the list under another account (debs_2018_gc), as well as cannot create new challenges, as have 0 systems possible to run for my benchmark. 

But I may simply Search the results by the `ChallengeTask=Query 1` or `ChallengeTask=Query 2` in results table, mark then and see details.
