### ISSUE TITLE
A benchmark without any parameters cannot be executed

### ISSUE THREAD

**Issue by mjovanovik** [hobbit-project/platform#339]
If the benchmark doesn't have any parameters, the platform GUI doesn't show the `Submit` button and therefore the benchmark cannot be executed.

**Comment by Ennosigaeon** [comment]
The submit button is available as soon as a benchmark and system are selected. The parameters are not relevant. Probably you have

1. Select a benchmark
2. Select a system
3. Switch benchmark

In this case, the system variable is reset, yet still selected in the dropdown. Therefore everything looks correct, but in fact no system is selected. I have changed the UI to make this behaviour explicit.

**Comment by Ennosigaeon** [comment]
Fix is available in pull request #342

**Comment by MichaelRoeder** [comment]
The issue seems to be correctly described. I created a dummy benchmark with which you can test the behavior. At least in the online platform, the button is missing after choosing the system (as written in the issue description)

![hobbit gui 20](https://user-images.githubusercontent.com/6122307/43458102-3cbca1a4-94c9-11e8-8fbf-35d0f6026a6b.png)
