### ISSUE TITLE
Return DNS name (or similar) instead of Task ID

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#370]
## Description

At the moment, the platform controller returns the task ID of a created container. This is not helpful for a user since he can not use it to connect to this container.

## Solution
- [x] Replace the task ID with something else that
    - can be used to identify the container / task / service (and remove it if necessary)
    - can be used to connect to the container
- [x] Test that a connection to the container based on the new identifier is working (e.g., a JUnit test would be good)
- [x] Change the other parts of the ContainerManagerImpl class which are based on the identifier (e.g., the stopping of containers)

**Comment by smirnp** [comment]
Not sure, that serviceID is connectable, since service can have multiple containers. 

[Here](https://github.com/hobbit-project/platform/blob/beec4a0f0ca97ce2484f4880671a84b8bb2a0ab5/platform-controller/src/main/java/org/hobbit/controller/docker/ContainerManagerImpl.java#L542) I already tried to return containerName, but for returned back to taskId, because of the problem below.

Currently struggling with problem that container id is changing in 1-2 seconds after service started. 
So if you would return the id of first container (which is killed after 1 second), then the platform would recognize it as failed and would stop the benchmark. That's why I returned back taskId instead of containerId/name.

I have noticed that implementing the [ServiceLogsReader](https://github.com/hobbit-project/platform/blob/cloud/platform-controller/src/main/java/org/hobbit/controller/utils/ServiceLogsReader.java), which listens all the containers created by service.

**Comment by denkv** [comment]
I'm on this issue right now and I'll probably go with using service name. It is connectable (even from non-service containers, as long as they're connected to the same docker network).

**Comment by smirnp** [comment]
Is it working fine?
I'm facing the problem that containerStateObserver reports that container stopped immediately, if I use serviceName instead of taskId (i'm replacing it in the cloud branch). Seems that containerStateOberver still needs containerId or taskId instead of serviceName
