### ISSUE TITLE
Problem with invoking evaluation module when scaling out over Data Generators

### ISSUE THREAD

**Issue by Kleanthi** [hobbit-project/platform#42]
While executing ODIN in the platform I notice the following:

- Population 1000, Number of streams apprx. 10 with 100 insert queries and 2 data gens: works fine

- Population 1000, Number of streams apprx. 10 with 100 insert queries and 10 data gens: all components are terminated successfully but no signal is sent to the evaluation storage to start the evaluation. As a result, the experiment terminates because it runs out of time.

**Comment by yamalight** [comment]
Testing is blocked due to #6

**Comment by yamalight** [comment]
The problem seems to be related to the fact that [SystemAdapter#close()](https://github.com/hobbit-project/odin/blob/master/src/main/java/org/hobbit/odin/systems/virtuoso/VirtuosoSystemAdapter.java#L230) method doesn't actually close all active connections. So, the container stays up and BenchmarkController waits for its termination indefinitely.

**Comment by MichaelRoeder** [comment]
That fits to the problem that Mirko and I have seen with another system adapter and that is described on the mailing list:
>I had problem with my System Adapter. Actually, the DataGen and TaskGen
finish their jobs very early, and System Adapter run after that for a
couple of minutes, executing all the queries. When it is done, the close()
method of the SystemAdapter has been executed, but the container with the
SystemAdapter hasn't been stopped after that, and BenchmarkController
waits forever for SystemAdapter to be terminated.

>The problem was in a pool of Threads that was still running, but it should
have been closed. Thanks to Michael, there is a workaround: Using the
ComponentStarter class that should force the termination after the close
method is executed:
https://github.com/hobbit-project/sparql-snb/commit/ca68647665c4f4259ef4b6bb362b7238afedf6dd

>If anyone has the similar issue, this workaround can be used.

Unfortunately, it is not clear were this thread pool is created.

**Comment by yamalight** [comment]
Using custom ComponentStarter fixes issue for ODIN.
I see two options:
1. Make that custom ComponentStarter into a default one (would also prevent future possible issues)
2. Just use it within ODIN

@MichaelRoeder thoughts?

**Comment by MichaelRoeder** [comment]
As a workaround, the costum ComponentStarter can be used. However, the error shows that there is a problem with resources that are not freed correctly, which is something we should try to avoid.

So my suggestion would be to 1) use the workaround, 2) reduce importance of issue (since we have a workaround) and 3) investigate the issue later on, when more important issues have been closed.

**Comment by yamalight** [comment]
ODIN issue was addressed in https://github.com/hobbit-project/odin/commit/18a4c17b930ab64cca6b104cdd505eea5ef05e13
Will lower the priority now.

**Comment by MichaelRoeder** [comment]
@Kleanthi is this issue still relevant? Did you tried to use the "normal" ComponentStarter instead of the workaround?

**Comment by Kleanthi** [comment]
I will check it once I am back from vacations.
However, currently we are using Mirko's system adapter.

**Comment by MichaelRoeder** [comment]
If you are not using this system adapter anymore and you didn't had the problem somewhere else, we can close the issue.
