### ISSUE TITLE
Challenge should be visible with only the last part of its URI

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#65]
## Feature description

Every challenge starts with the URI `http://w3id.org/hobbit/challenges#`. At the moment, a challenge will be loaded by the UI if the complete URI is present as argument, e.g., `http://master.project-hobbit.eu/#/challenges/http%3A%2F%2Fw3id.org%2Fhobbit%2Fchallenges%237023e350-9376-4d30-8a1e-2bbf1b639f27`.

Since we want to use w3id.org redirect rules to make the challenge URIs dereferencable (see https://github.com/perma-id/w3id.org/pull/714), it would be better to also accept the last part of the URI as argument, e.g., `http://master.project-hobbit.eu/#/challenges/7023e350-9376-4d30-8a1e-2bbf1b639f27`. This can be added with a simple if statement that checks whether the given ID starts with `http`. If not, `Constants.CHALLENGE_URI_NS` can be used to create the complete challenge URI.

**Comment by denkv** [comment]
As was discussed, redirects at `w3id.org` would need to be fixed since there is no way for a server-side redirect to check URL fragments. It's only possible to leave fragments as is while redirecting.

In current situation (if we can't change URLs at `w3id.org` and so far we keep URL fragment-routing in angular) we can mitigate that by adding intermediate pages with JavaScript redirects.

Maybe something like
`http://master.project-hobbit.eu/go/challenges#ID`
`http://master.project-hobbit.eu/go/experiments#ID`

**Comment by MichaelRoeder** [comment]
Looks good to me. Might be better than #81

**Comment by denkv** [comment]
Changes from https://github.com/hobbit-project/platform/issues/81 now also are able to handle URLs like `http://master.project-hobbit.eu/challenges/#UUID`, which is would redirect to `http://master.project-hobbit.eu/challenges/UUID` where we could handle them without much trobule.

**Comment by MichaelRoeder** [comment]
https://github.com/MichaelRoeder/w3id.org/tree/master/hobbit needs to be updated accordingly.

**Comment by MichaelRoeder** [comment]
Implemented and released with [v1.0.12](https://github.com/hobbit-project/platform/releases/tag/v1.0.12)
