### ISSUE TITLE
Task description overflows (not visible)

### ISSUE THREAD

**Issue by earthquakesan** [hobbit-project/platform#75]
![image](https://user-images.githubusercontent.com/1092829/28564802-735f6f52-712a-11e7-9c13-46cf894b464e.png)

**Comment by MichaelRoeder** [comment]
@romankorf @denkv Any ideas how to solve that in a good way?

I could imagine that we add a symbol at the end of the description (something like :heavy_plus_sign:) and if you hover it with the mouse, a bubble or tooltip shows the complete text.

**Comment by denkv** [comment]
Other table columns and other pages with similar tables have the same problem (example: http://master.project-hobbit.eu/#/challenges).

First, we should make it look better with `text-overlow: ellipsis` or similar.

Second, is there a need to be able to view full descriptions directly in these lists?

- On "challenges" page full description is available after chosing a challenge (on the challenge page). It would be fair to make sure full descriptions and other data are available after any item is selected.

- In heavily congested tables, like on "challenges" page (even date/time is being clipped there!), maybe we shouldn't include descriptions at all, ensuring they are available after any item is selected?

- Maybe try to set minimal column sizes for columns with data of known maximum length (like dates).

Also looking at current descriptions at `master.project-hobbit.eu`, maybe we can make up some guidelines and put them somewhere, since opening words like `The aim of this task is to` aren't helpful at all there, especially when description is being clipped.

**Comment by MichaelRoeder** [comment]
I have collected the different cases, in which descriptions of challenges and challenge tasks are shown.

@romankorf @denkv @yamalight please give comments, what you would suggest in the single cases.

### 1. Challenge Overview
In the list of challenges, the description of the challenge is visible but is being clipped.
![challengeoverview](https://user-images.githubusercontent.com/6122307/29331982-af86bec4-81fe-11e7-9f5c-de1d48daef0a.png)
As Denis already pointed out, the dates are much more important. However, I think the user has to be able to put the challenge into a category based on the information that can be found on this page (i.e., without opening the page of a challenge). Thus, I would argue for having tooltips containing the description or the :heavy_plus_sign: I described above.

Another detail I would like to change is that the challenges should be sorted ascending by their names in alphabetic order by default.

### 2. Challenge Details
In the page describing a single challenge in detail, the descriptions of the tasks are listed.
![challengedetails](https://user-images.githubusercontent.com/6122307/29332235-a4041b7c-81ff-11e7-90c6-29a68aab0faf.png)

To me, this already looks good. The only detail I would like to change is that the challenge tasks should be sorted ascending by their name in alphabetic order by default.

### 3. Challenge Results
On the page listing the tasks and their results, the challenge tasks are listed with their description.
![challengeresults](https://user-images.githubusercontent.com/6122307/29332424-4413897c-8200-11e7-809f-88077eae2eb6.png)

I would remove the description of the tasks from the list and show the description of a task below its name when the user selects it from the list. In the following example, the description would be printed below `Experiments for Task OKE2017 Task 2 Scenario B`.
![challengeresultsdetails](https://user-images.githubusercontent.com/6122307/29332451-5de35de6-8200-11e7-9c54-f1b75d0db5e9.png)

Additionally, I would also argue to have the tasks in a sorted order by default.

### 4. Challenge Registration
When registering vor a challenge, the user sees the description of a task and the descriptions for the systems he can register.
![registration](https://user-images.githubusercontent.com/6122307/29332746-5face72c-8201-11e7-8bcf-2de792c39f9e.png)

To me, the page looks fine, but we need to make sure that the tasks are sorted on this page in the same order as on the other pages. I couldn't test this now but I assume that they have no explicit order until now.

**Comment by MichaelRoeder** [comment]
Roman already submitted adaptations of the tables in f2e17d2d0516f471201bba3402b23b2778bac5b4 and 1a464b81164078f60100becbf372c4969e2e3a8a

**Comment by Ennosigaeon** [comment]
Again, changes are available as soon as #104 is merged.

**Comment by denkv** [comment]
I've added system names and descriptions on challenge registration screen, now all mentioned cases work as suggested.
