### ISSUE TITLE
"Parameter" table field in Experiments view (what is it?)

### ISSUE THREAD

**Issue by earthquakesan** [hobbit-project/platform#76]
"Parameter" should be changed to "Experiment ID".

![image](https://user-images.githubusercontent.com/1092829/28564860-a9b3470e-712a-11e7-968d-2094192ced01.png)

**Comment by romankorf** [comment]
The screenshot is missleading, I think it does not show the mentioned issue. However, the table headings where meant to read vertical instead of horizontal.

**Comment by MichaelRoeder** [comment]
Yes, the screenshot does not show the correct screen. I just created a new one.
![unbenannt](https://user-images.githubusercontent.com/6122307/28923870-d4e0c974-785f-11e7-9dc6-306c9c079876.png)

In an older version, the term "Parameter" fitted in the heading of the column. However, I agree with @earthquakesan that since we have "Experiment Parameter" in the same column, the word "Parameter" looks misplaced.

**Comment by romankorf** [comment]
changed in branch https://github.com/hobbit-project/platform/tree/feature/path-routing
